import random
from typing import TYPE_CHECKING, Any
from uuid import uuid4

if TYPE_CHECKING:
    from bizsim.product_catalog import ProductCatalog

try:
    from typing_extensions import override
except ImportError:
    from typing import override  # type: ignore

from bizsim.agents.base import BaseAgent
from bizsim.channels import InterAgentMessage
from bizsim.domain import ActionEvent, ReadPattern, TenantContext, WritePattern


class ConsumerAgent(BaseAgent):
    def __init__(
        self,
        agent_id: int,
        tenant_context: TenantContext,
        scheduling_config: dict[str, Any],
        profile: dict[str, Any],
        seed: int = 42,
        *,
        catalog: "ProductCatalog | None" = None,
        peer_agents: dict[str, int] | None = None,
        **kwargs: Any,
    ):
        super().__init__(
            agent_id,
            "consumer",
            tenant_context,
            scheduling_config,
            seed=seed,
            catalog=catalog,
            peer_agents=peer_agents,
        )
        self.profile = profile
        # profile contains: interest (dict), price_sensitivity (float), urgency (dict)
        self.cart: list[dict[str, Any]] = []
        self.pending_orders: dict[str, dict[str, Any]] = {}
        self.completed_orders: list[dict[str, Any]] = []
        self._skus_to_view: list[dict[str, Any]] = []
        self.rng = random.Random(seed + agent_id)

    def handle_shopping(self, tick: int) -> list[ActionEvent]:
        """Recurring shopping loop: browse -> view -> cart -> purchase."""
        return self.handle_browse_catalog(tick)

    def handle_browse_catalog(self, tick: int) -> list[ActionEvent]:
        """Step 1: Browse catalog based on interest."""
        # Weighted category selection
        categories = list(self.profile.get("interest", {}).keys())
        if not categories:
            return []

        weights = list(self.profile.get("interest", {}).values())
        category = self.rng.choices(categories, weights=weights, k=1)[0]

        # Ch.1 Event: consumer_browse
        # Correlated reads: browse_catalog, check_reviews
        read_patterns = [
            ReadPattern(pattern="browse_catalog", params={"category": category, "limit": 20}),
            # In a real scenario, we'd need SKU IDs for check_reviews,
            # but the spec says these are generated by the translator.
            # We'll just emit the browse event as per spec.
            ReadPattern(pattern="check_reviews", params={"category": category}),
        ]

        event = self._emitter.emit(event_type="consumer_browse", tick=tick, reads=read_patterns)

        if self.catalog:
            skus = self.catalog.browse_skus(category, limit=3)
            self._skus_to_view = [{"sku_id": s["sku_id"], "category": category} for s in skus]
        else:
            self._skus_to_view = []

        # Next tick, we'll run view_product.
        # Since the scheduling handles handle_shopping, we might need a state machine
        # or just call view_product if we have pending views.
        return [event]

    @override
    def step(self, tick: int) -> list[ActionEvent]:
        events = super().step(tick)

        # Handle pipeline continuations that aren't triggered by inbox or schedule
        if hasattr(self, "_skus_to_view") and self._skus_to_view:
            view_events = self.handle_view_product(tick)
            events.extend(view_events)
            self._skus_to_view = []

        return events

    def handle_view_product(self, tick: int) -> list[ActionEvent]:
        events: list[ActionEvent] = []
        for item in self._skus_to_view:
            sku_id = item["sku_id"]
            category = item["category"]
            # P_view check
            interest = self.profile.get("interest", {}).get(category, 0.1)
            # Simplification: trend_multiplier=1.0, novelty_factor=1.0
            p_view = min(max(interest, 0.0), 1.0)

            if self.rng.random() < p_view:
                req = self.emit_query(
                    query_template="product_details",
                    params={"sku_id": sku_id},
                    context={"sku_id": sku_id, "category": category},
                )
                events.append(
                    self._emitter.emit(event_type="query_request", tick=tick, queries=[req])
                )
        return events

    def on_product_details_result(
        self, data: dict[str, Any], context: dict[str, Any], tick: int
    ) -> list[ActionEvent]:
        """Step 3: Process product details, add to cart, and potentially purchase."""
        sku_id = context["sku_id"]
        category = context["category"]
        actual_price = data.get("current_price", 100.0)
        avg_review = data.get("avg_review", 4.0)

        base_price = 100.0
        if self.catalog:
            sku_data = self.catalog.get_sku(sku_id)
            if sku_data:
                base_price = sku_data.get("base_price", 100.0)

        price_sensitivity = self.profile.get("price_sensitivity", 1.0)

        price_ratio = (float(actual_price) - base_price) / base_price
        review_factor = min(avg_review / 4.0, 1.0)

        p_cart = min(max((1.0 - price_ratio * price_sensitivity) * review_factor, 0.0), 1.0)

        if self.rng.random() < p_cart:
            self.cart.append({"sku_id": sku_id, "category": category, "price": actual_price})

            urgency = self.profile.get("urgency", {}).get(category, 0.6)
            cart_abandonment_base = 0.25
            p_purchase = urgency * (1.0 - cart_abandonment_base)

            if self.rng.random() < p_purchase:
                return self._initiate_purchase(sku_id, 1, category, actual_price, tick)

        return []

    def _initiate_purchase(
        self, sku_id: int, qty: int, category: str, price: float, tick: int
    ) -> list[ActionEvent]:
        order_request_id = str(uuid4())

        seller_id = self.rng.randint(1, 10)
        if self.catalog:
            sellers = self.catalog.get_sellers_for_sku(sku_id)
            if sellers:
                seller_id = self.rng.choice([s["seller_id"] for s in sellers])

        self.pending_orders[order_request_id] = {
            "sku_id": sku_id,
            "qty": qty,
            "category": category,
            "price": price,
            "seller_id": seller_id,
            "status": "requested",
        }

        write_patterns = [
            WritePattern(
                pattern="insert_consumer_order",
                params={
                    "order_request_id": order_request_id,
                    "sku_id": sku_id,
                    "qty": qty,
                    "seller_id": seller_id,
                    "offered_price": price,
                    "status": "requested",
                },
            )
        ]

        msg = InterAgentMessage(
            msg_id=uuid4(),
            msg_type="place_order",
            from_agent=self.agent_id,
            to_agent=seller_id,
            from_tenant=self.tenant_id,
            tick_sent=tick,
            payload={
                "order_request_id": order_request_id,
                "sku_id": sku_id,
                "qty": qty,
                "offered_price": price,
            },
        )

        event = self._emitter.emit(
            event_type="consumer_purchase_intent", tick=tick, writes=write_patterns, messages=[msg]
        )

        return [event]

    def on_order_accepted(
        self, payload: dict[str, Any], from_agent: int, tick: int
    ) -> list[ActionEvent]:
        order_request_id = payload["order_request_id"]
        if order_request_id not in self.pending_orders:
            return []

        self.pending_orders[order_request_id]["status"] = "accepted"
        self.pending_orders[order_request_id]["store_order_id"] = payload["store_order_id"]

        write_patterns = [
            WritePattern(
                pattern="update_consumer_order",
                params={"order_request_id": order_request_id, "status": "accepted"},
            )
        ]

        msg = InterAgentMessage(
            msg_id=uuid4(),
            msg_type="payment",
            from_agent=self.agent_id,
            to_agent=from_agent,
            from_tenant=self.tenant_id,
            tick_sent=tick,
            payload={
                "order_request_id": order_request_id,
                "store_order_id": payload["store_order_id"],
                "amount": payload["confirmed_price"],
                "payer_id": self.agent_id,
            },
        )

        event = self._emitter.emit(
            event_type="consumer_order_status_update",
            tick=tick,
            writes=write_patterns,
            messages=[msg],
        )

        return [event]

    def on_shipment_notification(
        self, payload: dict[str, Any], from_agent: int, tick: int
    ) -> list[ActionEvent]:
        order_request_id = payload["order_request_id"]
        if order_request_id not in self.pending_orders:
            return []

        order = self.pending_orders.pop(order_request_id)
        order["status"] = "delivered"
        self.completed_orders.append(order)

        write_patterns = [
            WritePattern(
                pattern="update_consumer_order",
                params={"order_request_id": order_request_id, "status": "delivered"},
            )
        ]

        event = self._emitter.emit(
            event_type="consumer_order_status_update", tick=tick, writes=write_patterns
        )

        return [event]

    def handle_order_history_check(self, tick: int) -> list[ActionEvent]:
        req = self.emit_query(
            query_template="order_history",
            params={"consumer_id": self.agent_id, "window_days": 30},
            context={},
        )
        return [self._emitter.emit(event_type="query_request", tick=tick, queries=[req])]

    def on_order_history_result(
        self, data: dict[str, Any], context: dict[str, Any], tick: int
    ) -> list[ActionEvent]:
        events: list[ActionEvent] = []
        orders = data.get("orders", [])
        cancel_probability = 0.5

        for order_info in orders:
            if order_info.get("is_late") and order_info.get("status") == "requested":
                if self.rng.random() < cancel_probability:
                    order_request_id = order_info["order_request_id"]
                    events.extend(self._cancel_order(order_request_id, tick))
        return events

    def _cancel_order(self, order_request_id: str, tick: int) -> list[ActionEvent]:
        if order_request_id in self.pending_orders:
            self.pending_orders[order_request_id]["status"] = "cancel_requested"
            seller_id = self.pending_orders[order_request_id]["seller_id"]
        else:
            return []

        write_patterns = [
            WritePattern(
                pattern="update_consumer_order",
                params={"order_request_id": order_request_id, "status": "cancel_requested"},
            )
        ]

        msg = InterAgentMessage(
            msg_id=uuid4(),
            msg_type="cancel_request",
            from_agent=self.agent_id,
            to_agent=seller_id,
            from_tenant=self.tenant_id,
            tick_sent=tick,
            payload={
                "order_request_id": order_request_id,
                "consumer_id": self.agent_id,
                "reason": "late delivery",
            },
        )

        event = self._emitter.emit(
            event_type="consumer_order_status_update",
            tick=tick,
            writes=write_patterns,
            messages=[msg],
        )

        return [event]

    def on_cancel_confirmed(
        self, payload: dict[str, Any], from_agent: int, tick: int
    ) -> list[ActionEvent]:
        order_request_id = payload["order_request_id"]
        if order_request_id in self.pending_orders:
            order = self.pending_orders.pop(order_request_id)
            order["status"] = "cancelled"
            self.completed_orders.append(order)

        # Ch.1 Event: consumer_order_status_update
        write_patterns = [
            WritePattern(
                pattern="update_consumer_order",
                params={"order_request_id": order_request_id, "status": "cancelled"},
            )
        ]

        event = self._emitter.emit(
            event_type="consumer_order_status_update", tick=tick, writes=write_patterns
        )

        return [event]

    def on_cancel_rejected(
        self, payload: dict[str, Any], from_agent: int, tick: int
    ) -> list[ActionEvent]:
        order_request_id = payload["order_request_id"]
        if order_request_id in self.pending_orders:
            self.pending_orders[order_request_id]["status"] = "accepted"

        # Ch.1 Event: consumer_order_status_update
        write_patterns = [
            WritePattern(
                pattern="update_consumer_order",
                params={"order_request_id": order_request_id, "status": "accepted"},
            )
        ]

        event = self._emitter.emit(
            event_type="consumer_order_status_update", tick=tick, writes=write_patterns
        )

        return [event]
